/**:
  ros__parameters:

    drone:
      m: 2.9
      l: 0.265
      MoiArray: [0.060, 0.060, 0.080]
      motor_const: 1.465e-7
      moment_const: 0.01569

    dob:
      dob_looptime: 0.010
      eps_f: 0.01
      eps_tau: 0.01

    lpf:
      lin_vel_cutoff: 20.0
      ang_vel_cutoff: 60.0
      disturbance_force_cutoff: 60.0
      disturbance_torque_cutoff: 60.0

    topic_names:
      odom_in_topic: "/S550/ground_truth/odometry"
      filtered_odom_topic: "/hgdo/filtered_odom"
      actual_rpm_topic: "/uav/actual_rpm"
      dob_wrench_topic: "/hgdo/wrench"