/**:
  ros__parameters:

    drone:
      m: 2.9
      l: 0.265
      MoiArray: [0.060, 0.060, 0.080]
      motor_const: 1.465e-7
      moment_const: 0.01569

    dob:
      dob_looptime: 0.010
      eps_f: 0.05
      eps_tau: 0.05

    lpf:
      lin_vel_cutoff: 20.0
      ang_vel_cutoff: 60.0
      disturbance_force_cutoff: 60.0
      disturbance_torque_cutoff: 60.0

    topic_names:
      odom_in: "/mavros/local_position/odom"
      filtered_odom: "/hgdo/filtered_odom"
      actual_rpm: "/uav/rotor_state"
      dob_wrench: "/hgdo/wrench"