/**:
  ros__parameters:
    dynamic_param:
      m: 2.9
      MoiArray: [0.06, 0.06, 0.08]

    drone_param:
      arm_length: 0.265
      rotor_const: 1.465e-07
      moment_const: 0.01569
      T_max: 8.0
      T_min: 0.586

    nmpc_param:
      t_horizon: 1.0
      n_nodes: 20
      QArray: [ 20.0, 20.0, 20.0,        # px, py, pz
                12.0, 12.0, 12.0,        # vx, vy, vz
                12.0, 12.0, 12.0, 12.0,   # qw, qx, qy, qz
                5.0, 5.0, 5.0]     # wx, wy, wz
      R: [0.01]     # u1...u6

    sensor_time_param:
      timeout:
        rc: 0.10
        odom: 0.10
        do: 0.10